### ISSUE TITLE
debian镜像少了一个debian-security

### ISSUE THREAD

**Issue by bale0011** [SCAULUG/contributors#10]
需要添加一个：https://mirrors.scau.edu.cn/debian-security

可以参考中科大的镜像源：
中科大镜像源代链接：https://mirrors.ustc.edu.cn/

**Comment by Welkin-cf** [comment]
您好, [Debian Security 源 ](https://mirrors.scau.edu.cn/debian-security/)及相关[ 使用帮助 ](https://mirrors.scau.edu.cn/mirrors-help/openeuler.html)已上线。如果您在使用的过程中遇到任何问题，可以直接向 SCAULUG 提交 Issue。
