### ISSUE TITLE
能添加一个OpenWRT（LEDE）的镜像源吗

### ISSUE THREAD

**Issue by long45343** [SCAULUG/contributors#12]
官方源如下
访问速度实在是太慢了😂
src/gz openwrt_core https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/packages
src/gz openwrt_base https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base
src/gz openwrt_luci https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci
src/gz openwrt_packages https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages
src/gz openwrt_routing https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing
src/gz openwrt_telephony https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/telephony

**Comment by Welkin-cf** [comment]
不考虑同步, 可以到 [mirrorz-openwrt](https://mirrorz.org/list/openwrt) 页面选择合适的 OpenWrt/LEDE 软件包镜像源进行使用
