### ISSUE TITLE
The openEuler mirrors will update the rsync address

### ISSUE THREAD

**Issue by nicliuqi** [SCAULUG/contributors#13]
Hi, we have registered a new rsync address for the openEuler mirrors, and the old one will be replaced.

If your site is still using rsync://121.36.97.194/ as the rsync address, please change it to rsync://repo.openeuler.openatom.cn/openeuler/ and inform us. Thank you!

Synchronization command: rsync rsync://repo.openeuler.openatom.cn/openeuler/

Best regards,
Infrastructure team, openEuler community

**Comment by Welkin-cf** [comment]
您好, openEuler在近一年的镜像大小增长速度超过我们的预期, 增量在2T左右.  
且因目前存储空间已爆满, 我们预期于6.15停止同步并在7月前完成下架.

**Comment by nicliuqi** [comment]
好的，感谢一直以来的支持
