### ISSUE TITLE
网站的表述错了

### ISSUE THREAD

**Issue by long45343** [SCAULUG/contributors#18]
![Screenshot_2024-10-17-15-53-05-933_com microsoft emmx](https://github.com/user-attachments/assets/de0381cb-1fd7-41fd-8896-894ec18ef29e)
华南农业大学打反了😂

**Comment by locez** [comment]
![image](https://github.com/user-attachments/assets/fd4687d6-d577-4e77-8b54-b1d24b722007)
已经修复，感谢提醒
