### ISSUE TITLE
建议增加Linux Mint和Deepin的ISO文件镜像

### ISSUE THREAD

**Issue by mraandtux** [SCAULUG/contributors#3]
（注：本人为华南农大附近居民）
镜像名称：深度操作系统ISO文件
官方源地址：rsync://rsync.deepin.com::releases
镜像大小：3gb左右—— https://www.deepin.org/mirrors/setup-mirror-sites/
镜像名称：Linux Mint系统ISO文件
官方源地址：rsync://rsync-packages.linuxmint.com::packages
镜像大小：25gb左右—— https://linuxmint.com/mirrors.php
如果仍有空间可建议添加其上述系统的软件源，详见上述网站。

**Comment by aLittleFat** [comment]
非常感谢您的建议，我们将在近期内完成Linux Mint和Deepin的ISO文件镜像的添加和同步。

**Comment by HardworkFish** [comment]
> （注：本人为华南农大附近居民）
> 镜像名称：深度操作系统ISO文件
> 官方源地址：rsync：//rsync.deepin.com :: releases 
> 镜像大小：3gb左右 - [https://www.deepin.org / mirrors / setup-mirror-sites /](https://www.deepin.org/mirrors/setup-mirror-sites/)
> 镜像名称：Linux Mint系统ISO文件
> 官方源地址：rsync：//rsync-packages.linuxmint.com :: packages 
> 镜像大小：25gb左右 - [https://linuxmint.com/ mirrors.php](https://linuxmint.com/mirrors.php)
> 如果仍有空间可建议添加其上述系统的软件源，详见上述网站。

--------------------
非常感谢您的建议，我们已完成Linux Mint和Deepin的ISO文件镜像的添加和同步。您可以到 [Scau Mirros](https://mirrors.scau.edu.cn/) 主页访问并获取，感谢您的支持。
