### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by lsz66** [SCAULUG/contributors#5]
你好，现在是2019.4.24 14:34，刚刚我想通过apt下载软件发现连接不到服务器，直接访问主页提示找不到 mirrors.scau.edu.cn 的服务器 IP 地址。

**Comment by imquanquan** [comment]
谢谢反馈，刚刚学校网络出现问题，外网无法解析 mirrors.scau.edu.cn 域名，正在向学校现代教育技术中心反馈修复。

**Comment by imquanquan** [comment]
网络已恢复正常，我先把 Issues 关了，后续有任何问题可以重开。thanks
