### ISSUE TITLE
请求添加openEuler官方镜像源

### ISSUE THREAD

**Issue by zhang-jian-jun** [SCAULUG/contributors#7]
镜像名:
openEuler官方镜像源

镜像简介：
华南农业大学开源镜像站点，你们好！
我们是来自于openEuler[ https://openeuler.org/zh/ ]开源操作系统社区的基础设施团队, openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展。当前openEuler社区有自己的发布仓库[ https://repo.openeuler.org/ ]，想咨询下能否在你们的镜像源上面支持openEuler社区的镜像呢？多谢！

我们提供openEuler镜像同步指令如下:
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
秘钥信息: root:openeuler@1234 (只读账户)

openEuler社区基础设施团队
[1]: https://openeuler.org/zh/
[2]: https://repo.openeuler.org/
镜像大小:
多个版本共600G

**Comment by locez** [comment]
我们这边需要评估我们学校是否有必要上，但是针对上面提到的问题是：

我们肯定是不会支持 ip 地址的形式加入到我们的镜像中的，我们无法验证 ip 地址的owner， 但是通过域名，我们可以认证所有者。 因此如果后续评估可以加入的话， 一定需要提供域名的方式

**Comment by TommyLike** [comment]
> 我们这边需要评估我们学校是否有必要上，但是针对上面提到的问题是：
> 
> 我们肯定是不会支持 ip 地址的形式加入到我们的镜像中的，我们无法验证 ip 地址的owner， 但是通过域名，我们可以认证所有者。 因此如果后续评估可以加入的话， 一定需要提供域名的方式

你好，我们是openeuler基础设施团队的，由于社区目前选用org作为域名，不能备案，且无法指向国内的机器，所以我们暂时还不能绑定域名信息，如果后续有备案的域名我们会第一时间提醒你们更新，麻烦！

**Comment by locez** [comment]
表示理解，但是我们同样希望认证你们的身份，可以使用 org 后缀的邮箱，重新发一封申请到 mirrors@scau.edu.cn 么？

**Comment by zhang-jian-jun** [comment]
你好，我们官网[https://openeuler.org/zh/]上面备注的邮箱是contact@openeuler.io  因为contact是给用户联系用的  我们已使用admin@openeuler.io给你发了一封申请邮件，到mirrors@scau.edu.cn ，请查收

**Comment by locez** [comment]
您好，我们已经沟通准备加上， 但是如果上游更改了 ip， 务必请及时到 issue 反馈， 避免下游更新失败的问题~

**Comment by zhang-jian-jun** [comment]
好的，感谢，如果ip变动第一时间反馈过来

**Comment by Welkin-cf** [comment]
> 镜像名:
> openEuler官方镜像源
> 
> 镜像简介：
> 华南农业大学开源镜像站点，你们好！
> 我们是来自于openEuler[ https://openeuler.org/zh/ ]开源操作系统社区的基础设施团队, openEuler旨在通过社区合作，打造创新平台，构建支持多处理架构、统一和开放的操作系统，推动软硬件应用生态繁荣发展。当前openEuler社区有自己的发布仓库[ https://repo.openeuler.org/ ]，想咨询下能否在你们的镜像源上面支持openEuler社区的镜像呢？多谢！
> 
> 我们提供openEuler镜像同步指令如下:
> rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
> 秘钥信息: root:openeuler@1234 (只读账户)
> 
> openEuler社区基础设施团队
> [1]: https://openeuler.org/zh/
> [2]: https://repo.openeuler.org/
> 镜像大小:
> 多个版本共600G

您好, 我们已完成 openEuler 镜像源的添加和同步, 可到 [openEuler](https://mirrors.scau.edu.cn/openeuler/) 查看

**Comment by zhang-jian-jun** [comment]
您好，非常感谢！

**Comment by Welkin-cf** [comment]
如果需要补充相应帮助文档, 请参考 [Mirrors-Help](https://github.com/SCAULUG/Mirrors-Help/tree/master/source) 提交pr 或 直接将文档发送到 mirrors@scau.edu.cn 。

**Comment by zhang-jian-jun** [comment]
您好！ 帮助文档已发送到mirrors@scau.edu.cn， 请查收

**Comment by Welkin-cf** [comment]
您好, 已补充 [openEuler-Help](https://mirrors.scau.edu.cn/mirrors-help/openeuler.html) 和 [contributor](https://mirrors.scau.edu.cn/mirrors-help/contributor.html)

**Comment by zhang-jian-jun** [comment]
@Welkin-cf 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

**Comment by Welkin-cf** [comment]
> @Welkin-cf 咨询openEuler镜像源限制的下载带宽是多少kb？我们这边做一个统计信息，谢谢哈

你好, 下载带宽为1000Mb/s

**Comment by zhang-jian-jun** [comment]
好的，谢谢哈

**Comment by zhang-jian-jun** [comment]
@Welkin-cf ，咨询一下，镜像站点，有没有提供我们这边统计openEuler镜像源资源下载量的接口或者数据导出功能？

**Comment by Welkin-cf** [comment]
> @Welkin-cf ，咨询一下，镜像站点，有没有提供我们这边统计openEuler镜像源资源下载量的接口或者数据导出功能？

你好, 暂时没有相关接口, 后续如果提供了接口会在此issue下回复你

**Comment by zhang-jian-jun** [comment]
好的，谢谢！

**Comment by zhang-jian-jun** [comment]
@Welkin-cf ，
非常感谢使用我们openEuler镜像源，镜像源的同步指令，不再需要用户名和密码，
直接输入：
rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
即可完成镜像源的同步，
谢谢！

**Comment by Welkin-cf** [comment]
> @Welkin-cf ，
> 非常感谢使用我们openEuler镜像源，镜像源的同步指令，不再需要用户名和密码，
> 直接输入：
> rsync -av --partial --progress rsync://root@121.36.97.194/openeuler
> 即可完成镜像源的同步，
> 谢谢！

你好, 已进行调整.
