### ISSUE TITLE
请求添加Termux官方镜像源

### ISSUE THREAD

**Issue by 2096779623** [SCAULUG/contributors#8]
# 镜像名称
Termux

# 镜像简介
Termux 是一款Android 终端模拟器和 Linux 环境应用程序，无需 root 或设置即可直接运行。自动安装最小的基本系统 - 使用 APT 包管理器可以使用其他包。

# 镜像大小
15GB

# 同步方式
https://github.com/termux/termux-packages/wiki/How-to-mirror-the-official-repositories

**Comment by Welkin-cf** [comment]
您好，我们将在近期同步并上线Termux源

**Comment by Welkin-cf** [comment]
[Termux 源 ](https://mirrors.scau.edu.cn/termux/)和[ Termux 源使用帮助 ](https://mirrors.scau.edu.cn/mirrors-help/termux.html)已上线， 如果您在使用的过程中遇到任何问题，可以直接向 SCAULUG 提交 Issue。
