### ISSUE TITLE
openEuler源添“help”中有EPOL项有错误

### ISSUE THREAD

**Issue by bale0011** [SCAULUG/contributors#9]
链接：https://mirrors.scau.edu.cn/mirrors-help/openeuler.html

其中：
[EPOL]
name=EPOL
baseurl=https://mirrors.scau.edu.cn/openeuler/openEuler-20.09/EPOL/$basearch/
enabled=1
gpgcheck=1
gpgkey=https://mirrors.scau.edu.cn/openeuler/openEuler-20.09/EPOL/$basearch/RPM-GPG-KEY-openEuler

应该要改为：
[EPOL]
name=EPOL
baseurl=https://mirrors.scau.edu.cn/openeuler/openEuler-22.03-LTS/EPOL/main/$basearch/
enabled=1
gpgcheck=1
gpgkey=https://mirrors.scau.edu.cn/openeuler/openEuler-22.03-LTS/OS/$basearch/RPM-GPG-KEY-openEuler

（baseurl这一行EPOL后面有一个main,
   gpgkey这一行如EPOL需要改为OS.）

**Comment by Welkin-cf** [comment]
您好，我们这边需要确认一下，稍晚点进行更新。

**Comment by Welkin-cf** [comment]
[openEuler 源使用帮助 ](https://mirrors.scau.edu.cn/mirrors-help/openeuler.html) 已更新。
